//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dolhouse.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dolhouse.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Full credits to:
        ///# arookas, SpaceCats64
        ///
        ///# Orientation
        ///pos_x
        ///pos_y
        ///pos_z
        ///dir_x
        ///dir_y
        ///dir_z
        ///scale_x
        ///scale_y
        ///scale_z
        ///
        ///# Identification
        ///name
        ///dmd_name
        ///path_name
        ///create_name
        ///character_name
        ///access_name
        ///CodeName
        ///
        ///# Generic arguments
        ///arg0
        ///arg1
        ///arg2
        ///arg3
        ///arg4
        ///arg5
        ///arg6
        ///arg7
        ///arg8
        ///
        ///# Point
        ///pnt0_x
        ///pnt0_y
        ///pnt0_z
        ///
        ///# Furniture
        ///furniture_x
        ///furniture_y
        ///furniture_z
        ///
        ///# Unsorted
        ///poly_material
        ///use
        ///next
        ///appear_point
        ///move
        ///move_level
        ///not_transparent
        ///generate
        ///generate_num
        ///furniture_sound
        ///telesa_hide
        ///telesa_appear
        ///sheet
        ///sheet_gum
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jmp {
            get {
                return ResourceManager.GetString("jmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7438,sAlphaSpeed,1
        ///15116,mFlagOnId,1
        ///3606,sAppearAngle,2
        ///12753,mCheckBox,2
        ///23818,mTimeOnNoDmage,2
        ///24887,mOmega,2
        ///24926,sOmega,2
        ///28929,mAttackType,2
        ///29336,sClinchOmega,2
        ///41148,mFlag,2
        ///44491,mTime,2
        ///45730,mDist,2
        ///49216,mBright,2
        ///1122,mBlinkFeq,4
        ///1193,mActAfterAttackFa,4
        ///1683,mTailLife,4
        ///1923,mHasCoin,4
        ///1971,sFrameAttackReady,4
        ///4541,mActAfterAttackSu,4
        ///5610,mReplaceFrame,4
        ///5901,sFrameJibaku2,4
        ///8024,mAttackPattern1,4
        ///8025,mAttackPattern2,4
        ///9512,mHitDamage,4
        ///9989,sFrameJibakuPlus,4
        ///11818 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string prm {
            get {
                return ResourceManager.GetString("prm", resourceCulture);
            }
        }
    }
}
